// English (openfootball) → 中文 national team names. Falls back to the English
// name for anything unmapped (incl. knockout placeholders like "2A" / "W73").

const TEAM_ZH: Record<string, string> = {
  // Hosts
  USA: "美国",
  "United States": "美国",
  Mexico: "墨西哥",
  Canada: "加拿大",
  // Europe
  Spain: "西班牙",
  France: "法国",
  England: "英格兰",
  Germany: "德国",
  Portugal: "葡萄牙",
  Netherlands: "荷兰",
  Italy: "意大利",
  Belgium: "比利时",
  Croatia: "克罗地亚",
  Switzerland: "瑞士",
  Denmark: "丹麦",
  Austria: "奥地利",
  "Czech Republic": "捷克",
  Czechia: "捷克",
  Serbia: "塞尔维亚",
  Poland: "波兰",
  Ukraine: "乌克兰",
  Sweden: "瑞典",
  Wales: "威尔士",
  Scotland: "苏格兰",
  Norway: "挪威",
  Turkey: "土耳其",
  Türkiye: "土耳其",
  Greece: "希腊",
  Hungary: "匈牙利",
  Romania: "罗马尼亚",
  Slovakia: "斯洛伐克",
  Slovenia: "斯洛文尼亚",
  "Bosnia & Herzegovina": "波黑",
  "Bosnia and Herzegovina": "波黑",
  Albania: "阿尔巴尼亚",
  "Republic of Ireland": "爱尔兰",
  Ireland: "爱尔兰",
  Russia: "俄罗斯",
  Finland: "芬兰",
  Iceland: "冰岛",
  "North Macedonia": "北马其顿",
  Montenegro: "黑山",
  Georgia: "格鲁吉亚",
  Israel: "以色列",
  // South America
  Brazil: "巴西",
  Argentina: "阿根廷",
  Uruguay: "乌拉圭",
  Colombia: "哥伦比亚",
  Chile: "智利",
  Peru: "秘鲁",
  Ecuador: "厄瓜多尔",
  Paraguay: "巴拉圭",
  Bolivia: "玻利维亚",
  Venezuela: "委内瑞拉",
  // CONCACAF
  "Costa Rica": "哥斯达黎加",
  Panama: "巴拿马",
  Jamaica: "牙买加",
  Honduras: "洪都拉斯",
  "El Salvador": "萨尔瓦多",
  Guatemala: "危地马拉",
  Haiti: "海地",
  "Trinidad & Tobago": "特立尼达和多巴哥",
  "Trinidad and Tobago": "特立尼达和多巴哥",
  Curaçao: "库拉索",
  Curacao: "库拉索",
  Suriname: "苏里南",
  // Africa
  Morocco: "摩洛哥",
  Senegal: "塞内加尔",
  Tunisia: "突尼斯",
  Algeria: "阿尔及利亚",
  Egypt: "埃及",
  Nigeria: "尼日利亚",
  Ghana: "加纳",
  Cameroon: "喀麦隆",
  "Ivory Coast": "科特迪瓦",
  "Côte d'Ivoire": "科特迪瓦",
  Mali: "马里",
  "South Africa": "南非",
  "DR Congo": "刚果（金）",
  "Cape Verde": "佛得角",
  "Cabo Verde": "佛得角",
  "Burkina Faso": "布基纳法索",
  Angola: "安哥拉",
  Gabon: "加蓬",
  Zambia: "赞比亚",
  Guinea: "几内亚",
  // Asia
  Japan: "日本",
  "South Korea": "韩国",
  "Korea Republic": "韩国",
  Iran: "伊朗",
  "IR Iran": "伊朗",
  Australia: "澳大利亚",
  "Saudi Arabia": "沙特阿拉伯",
  Qatar: "卡塔尔",
  Iraq: "伊拉克",
  "United Arab Emirates": "阿联酋",
  UAE: "阿联酋",
  Uzbekistan: "乌兹别克斯坦",
  Jordan: "约旦",
  China: "中国",
  "China PR": "中国",
  Oman: "阿曼",
  Bahrain: "巴林",
  "North Korea": "朝鲜",
  Indonesia: "印度尼西亚",
  Vietnam: "越南",
  Thailand: "泰国",
  // Oceania
  "New Zealand": "新西兰",
  "New Caledonia": "新喀里多尼亚",
  Tahiti: "塔希提",
};

export function teamName(name: string, lang: string): string {
  if (lang !== "zh") return name;
  return TEAM_ZH[name] ?? name;
}

// ISO 3166-1 alpha-2 codes for flagcdn.com (England/Scotland/Wales use the
// gb-* subdivision codes flagcdn supports).
const TEAM_CODE: Record<string, string> = {
  USA: "us",
  "United States": "us",
  Mexico: "mx",
  Canada: "ca",
  Spain: "es",
  France: "fr",
  England: "gb-eng",
  Germany: "de",
  Portugal: "pt",
  Netherlands: "nl",
  Italy: "it",
  Belgium: "be",
  Croatia: "hr",
  Switzerland: "ch",
  Denmark: "dk",
  Austria: "at",
  "Czech Republic": "cz",
  Czechia: "cz",
  Serbia: "rs",
  Poland: "pl",
  Ukraine: "ua",
  Sweden: "se",
  Wales: "gb-wls",
  Scotland: "gb-sct",
  Norway: "no",
  Turkey: "tr",
  Türkiye: "tr",
  Greece: "gr",
  Hungary: "hu",
  Romania: "ro",
  Slovakia: "sk",
  Slovenia: "si",
  "Bosnia & Herzegovina": "ba",
  "Bosnia and Herzegovina": "ba",
  Albania: "al",
  "Republic of Ireland": "ie",
  Ireland: "ie",
  Russia: "ru",
  Finland: "fi",
  Iceland: "is",
  "North Macedonia": "mk",
  Montenegro: "me",
  Georgia: "ge",
  Israel: "il",
  Brazil: "br",
  Argentina: "ar",
  Uruguay: "uy",
  Colombia: "co",
  Chile: "cl",
  Peru: "pe",
  Ecuador: "ec",
  Paraguay: "py",
  Bolivia: "bo",
  Venezuela: "ve",
  "Costa Rica": "cr",
  Panama: "pa",
  Jamaica: "jm",
  Honduras: "hn",
  "El Salvador": "sv",
  Guatemala: "gt",
  Haiti: "ht",
  "Trinidad & Tobago": "tt",
  "Trinidad and Tobago": "tt",
  Curaçao: "cw",
  Curacao: "cw",
  Suriname: "sr",
  Morocco: "ma",
  Senegal: "sn",
  Tunisia: "tn",
  Algeria: "dz",
  Egypt: "eg",
  Nigeria: "ng",
  Ghana: "gh",
  Cameroon: "cm",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  Mali: "ml",
  "South Africa": "za",
  "DR Congo": "cd",
  "Cape Verde": "cv",
  "Cabo Verde": "cv",
  "Burkina Faso": "bf",
  Angola: "ao",
  Gabon: "ga",
  Zambia: "zm",
  Guinea: "gn",
  Japan: "jp",
  "South Korea": "kr",
  "Korea Republic": "kr",
  Iran: "ir",
  "IR Iran": "ir",
  Australia: "au",
  "Saudi Arabia": "sa",
  Qatar: "qa",
  Iraq: "iq",
  "United Arab Emirates": "ae",
  UAE: "ae",
  Uzbekistan: "uz",
  Jordan: "jo",
  China: "cn",
  "China PR": "cn",
  Oman: "om",
  Bahrain: "bh",
  "North Korea": "kp",
  Indonesia: "id",
  Vietnam: "vn",
  Thailand: "th",
  "New Zealand": "nz",
  "New Caledonia": "nc",
  Tahiti: "pf",
};

// Flag image URL (flagcdn.com), or null for unmapped names / knockout codes.
export function teamFlagUrl(name: string, size: 20 | 40 = 20): string | null {
  const code = TEAM_CODE[name];
  if (!code) return null;
  const w = size === 40 ? "w80" : "w40";
  return `https://flagcdn.com/${w}/${code}.png`;
}
